config/routes.rb
Upstairs::Application.routes.draw do
  
  resources :involvements, :only => [:new, :create, :destroy]
  resources :roles, :only => [:index, :new, :create, :destroy]
  resources :groups

  resources :users do
    get 'avatar_cropping', :on => :member
  end
  
  resources :sessions, :only => [:new, :create, :destroy]
  
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/auth/:provider/callback', :to => 'sessions#callback'
  match '/auth/failure', :to => 'sessions#failure'
  
  root :to => 'pages#home'
end

app/models/group.rb
# == Schema Information
# Schema version: 20101118183705
#
# Table name: groups
#
#  id              :integer         not null, primary key
#  name            :string(255)
#  group_type      :string(255)
#  citation        :string(255)
#  citation_author :string(255)
#  aim_of_project  :string(255)
#  client          :string(255)
#  web_page        :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#

class Group < ActiveRecord::Base
  # citation should be removed, it sucks IMO -- Andrew
  
  attr_accessible :name, :group_type, :citation, :citation_author, 
                  :aim_of_project, :client, :web_page   
  
  url_regexp = /((http|https):\/\/\w+.\w+)|^$/i  #the most simple url validator
  
  validates :name, :presence => true, :uniqueness => true,
            :length => { :minimum => 8, :maximum => 50 }
  validates :group_type, :presence => true, :inclusion => ["PROJECT", "GROUP"]
  validates :citation, :presence => true, :unless => :citation_author_empty? 
  validates :web_page, :length => { :maximum => 50 }, :format => { :with => url_regexp }
  validates :client, :presence => true, :length => { :minimum => 4, :maximum => 50 }
  
  def citation_author_empty?
    citation_author.empty?
  end
  
  def participants 
    self.users.group("email, first_name, second_name").order("first_name, second_name")
  end
  
  
  has_many :involvements, :dependent => :destroy
  has_many :current_involvements, :class_name => "Involvement", :conditions => ['end_date is null']
  
  has_many :users, :through => :involvements, :source => :user
  
#  def involve (args)
  #   self.involvements.create(args)
  # end 
  # 
  # def terminate_involvement (args)
  #   self.involvements.create(args)
  # end 
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  
  before_filter :authenticate, :except => [:index]
  
  def new
    @group = Group.new
    @title = "Create a new group"
  end
  
  def index
    @groups = Group.all
    @title = "All groups"
  end

  def show
    @group = Group.find(params[:id])
    @title = "View group '#{@group.name}'."
    @involvements = @group.involvements.includes(:role, :user)
    @roles = Role.all
    @involvement = @group.involvements.new({:user_id => current_user.id, 
                                            :start_date => Date.today})
  end

  def create
    @group = Group.new(params[:group])
    if @group.save
       flash[:success] = "New group '#{@group.name}' was created."
       redirect_to group_path(@group)
    else
       @title = "Create a new group"
       render 'new'
    end
  end
  
  def destroy
    Group.find(params[:id]).destroy
    flash[:success] = "Group was removed"
    redirect_to groups_path
  end
  
  def edit
    @group = Group.find(params[:id])
    @title = "Edit #{@group.group_type.capitalize} #{@group.name}"
  end 
  
  def update
    @group = Group.find(params[:id])
    if @group.update_attributes(params[:group])
      flash[:success] = "Profile was updated."
      redirect_to group_path(@group)
    else
      @title = "Edit user"
      render 'edit'
    end
  end

#  def avatar_cropping
#   @title = "Group avatar cropping"
#   @group = Group.find(params[:id])
#   unless @group.avatar.exists?
#     redirect_to edit_group_url(@user)
#   end
#  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_involvements.html.erb
<div id="involvements">
  <% if @involvements.length > 0 %>
    <table> 
    <tr> 
      <th>Name</th> 
      <th>Role</th> 
      <th>Technology</th> 
      <th>Start Date</th> 
      <th>End Date</th>
      <th></th> 
    </tr> 
    <% @involvements.each do |i| %>
      <tr>
      <td><%="#{i.user.first_name} #{i.user.second_name}"%></td>      
      <td><%=i.role_name_full%></td>      
      <td><%=i.role_tech%></td>      
      <td><%=i.start_date%></td>      
      <td><%=i.end_date%></td>      
      <td>
        <% if i.user == current_user %>
          <%= form_for i, :html => {:method => :delete}, :remote => true do |f| %>
          <%= f.submit "Delete" %>    
          <% end %>
        <% end %>
      </td>
      </tr>      
    <% end %>
    </table>
  <% end %>
</div>  

app/views/groups/_participants.html.erb
<div id="participants">
  <h2>Participants</h2>
  <% @group.participants.each do |user| %>
    <p><%="#{user.first_name} #{user.second_name}"%></p>
  <% end %>
</div>

app/views/groups/edit.html.erb
<h1>Update <%= "#{@group.group_type.capitalize} #{@group.name}" %></h1>

<%= simple_form_for @group do |f| %>
  <%= f.input :name %>
  <%= f.input :group_type, :collection => ["PROJECT", "GROUP"] %>
  <%= f.input :citation, :as => :text %>
  <%= f.input :citation_author %>
  <%= f.input :aim_of_project %>
  <%= f.input :client %>
  <%= f.input :web_page %>
  <%= f.button :submit, "Update" %>
<% end %>

app/views/groups/index.html.erb
<h1>All groups</h1>
<ul class="groups">
<div><%= link_to "Create New Group", new_group_path%></div>  
<% @groups.each do |f| %>
  <li> 
    <h2><%= "#{f.group_type.capitalize}:#{f.name}" %></h2>
    <% unless f.citation.empty? %>
      <p class="citation"><%= f.citation %></p>
      <p class="citation_author"><%= f.citation_author %></p>
    <% end %>
    <% unless f.aim_of_project.empty? %>
      <p><strong>Aim:</strong><%= f.aim_of_project %></p>
    <% end %>
    <p><strong>Client:</strong><%= f.client %></p>
    <% unless f.web_page.empty? %>
      <p><strong>Web Page:</strong><%= f.web_page %></p>
    <% end %>
    <%= link_to "More...", group_path(f) %>
  </li>
<% end %>
</ul>

app/views/groups/new.html.erb
<h1><%= @title %></h1>

<%= simple_form_for @group do |f| %>
  <%= f.input :name %>
  <%= f.input :group_type, :collection => ["PROJECT", "GROUP"] %>
  <%= f.input :citation, :as => :text %>
  <%= f.input :citation_author %>
  <%= f.input :aim_of_project %>
  <%= f.input :client %>
  <%= f.input :web_page %>
  <%= f.button :submit %>
<% end %>

app/views/groups/show.html.erb
<h1><%= "#{@group.group_type.capitalize} #{@group.name}."%></h1>
<% unless @group.citation.empty? %>
  <p class="citation"><%= @group.citation %></p>
  <p class="citation_author"><%= @group.citation_author %></p>
<% end %>
<p><strong>Aim:</strong><%= @group.aim_of_project %></p>
<p><strong>Client:</strong><%= @group.client %></p>
<% unless @group.web_page.empty? %>
  <p><strong>Web Page:</strong><%= @group.web_page %></p>
<% end %>

<%= render 'involvements' %>

<%= link_to "Join", "#", html_options = {:id => "join_group"} %>
<%= link_to "Create Involvement", new_involvement_path(:group_id => @group.id) %>
<%= link_to "Edit", edit_group_path(@group)%>
<%= link_to "Delete", @group, :method => :delete %>

<%= render 'participants' %>

<%= render 'involvements/new_form' %>
<%= javascript_include_tag "jquery-ui-1.8.6.custom.min" %>
<%= stylesheet_link_tag "smoothness/jquery-ui-1.8.6.custom.css" %>
<script>
$(document).ready(function() {
  $('#new_involvement').dialog({ autoOpen: false, modal: true })
  $('#new_involvement').attr("data-remote","true")
  $('#join_group').click(function()
    $('#new_involvement').dialog({ autoOpen: true })
  )
  $('#new_involvement #involvement_submit').click (function(){
    $('#new_involvement').dialog("close");
  })
});
</script>


              