config/routes.rb
Upstairs::Application.routes.draw do
  
  resources :involvements, :only => [:new, :create, :destroy]
  resources :roles, :only => [:index, :new, :create, :destroy]
  resources :groups

  resources :users do
    get 'avatar_cropping', :on => :member
  end
  
  resources :sessions, :only => [:new, :create, :destroy]
  
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/auth/:provider/callback', :to => 'sessions#callback'
  match '/auth/failure', :to => 'sessions#failure'
  
  root :to => 'pages#home'
end

app/models/role.rb
# == Schema Information
# Schema version: 20101118183705
#
# Table name: roles
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  tech       :string(255)
#  role_type  :string(255)
#  area       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Role < ActiveRecord::Base
  attr_accessible :name, :tech, :role_type, :area
  validates :name, :presence => true, :uniqueness => true
  validates :area, :presence => true
  
  
  
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  
  def index
    @roles = Role.all
    @title = "Roles"
  end
  
  def new
    @role = Role.new();
    @title = "Create a new role"
  end
  
  def create
    @role = Role.new(params[:role])
    if @role.save
       flash[:success] = "New role '#{@role.name}' was created."
       redirect_to roles_path
    else
       @title = "Create a new role"
       render 'new'
    end    
  end
  
  def destroy
    Role.find_by_id(params[:id]).destroy
    redirect_to roles_path
  end

end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/index.html.erb
<h1>All Roles</h1>
<table class="roles">
<tr> 
  <th>Role Name</th>
  <th>Role Area</th>
  <th>Technology</th>
  <th>Role Type</th>
  <th></th>
<tr>
<%= link_to "Create New Role", new_role_path%></div>  
<% @roles.each do |role| %>
  <tr>
  	<td><%=role.name%></td>
  	<td><%=role.area%></td>
  	<td><%=role.tech%></td>
  	<td><%=role.role_type%></td>
  	<td><%= link_to "Delete", role, :method => :delete %></td>
  </tr>
<% end %>
</table>

app/views/roles/new.html.erb
<h1>Create new role</h1>

<%= simple_form_for @role do |f| %>
  <%= f.input :name %>
  <%= f.input :tech %>
  <%= f.input :role_type %>
  <%= f.input :area %>
  <%= f.button :submit %>
<% end %>  