config/routes.rb
Upstairs::Application.routes.draw do
  
  resources :involvements, :only => [:new, :create, :destroy]
  resources :roles, :only => [:index, :new, :create, :destroy]
  resources :groups

  resources :users do
    get 'avatar_cropping', :on => :member
  end
  
  resources :sessions, :only => [:new, :create, :destroy]
  
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/auth/:provider/callback', :to => 'sessions#callback'
  match '/auth/failure', :to => 'sessions#failure'
  
  root :to => 'pages#home'
end

app/views/layouts/_header.html.erb
<header>
	<nav id="top-nav">
		<logo>
			<%= link_to "upstairs", root_path %>
		</logo>
		<% if signed_in? %>
		<ul>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "Profile", user_path(current_user) %></li>
			<li><%= link_to "Sign out", signout_path, :method => :delete %></li>
		</ul>
		<% end%>
	</nav>
</header>

app/views/layouts/_notification.html.erb
<% flash.each do |key, value| %>
	<%= content_tag(:div, value, :class => "flash #{key}")%>
<% end %>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
	<script src = "http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->    
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Upstairs | <%= @title %></title>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <%= render :partial => 'layouts/stylesheets' %>
	<%= yield :head %>
</head>
<body>
	<div id="top-bar" class="gradient-bg"></div>	
	<div class = "container"> 
		<div class = "span-24 last">
			<%= render 'layouts/header' %>
		</div>

		<div class="span-24 last main-content">
			<% if signed_in? %>
			<div class = "span-6 colborder">
			  <% if @context = 'group'%>
   				<%= render :partial => "shared/group_panel" %>
  			<% else %>	
  				<%= render :partial => "shared/user_panel" %>
  			<% end %>		
			</div>
			<div class="span-17 last">
				<%= render :partial => 'layouts/notification' %>	
				<%= yield %>
			</div>
			<% else %>
			<div class="span-24 last">
				<%= render :partial => 'layouts/notification' %>
				<%= yield %>
			</div>
			<% end %>		
		</div>		
		
		<div class="span-24 last">
			<!--footer-->
			<%= debug(params) if Rails.env.development? %>
		</div>
	</div>
</body>
</html>